### ISSUE TITLE
sdbus++ generates invalid code for methods without return value

### ISSUE THREAD

**Issue by milindur** [openbmc/sdbusplus#3]
When defining an interface with a method without return value, e.g.

```yaml
description: >
    An example interface
methods:
    - name: ping
      description: >
        Takes a string argument and returns nothing.
      parameters:
        - name: name
          type: string
          description: >
            The string argument.
```

the sdbus++ tool generates invalid code:

```c++
namespace details
{
namespace TestService
{
static const auto _param_Ping =
        utility::tuple_to_array(message::types::type_id<
                std::string>());
static const auto _return_Ping =
        utility::tuple_to_array(message::types::type_id<
                >());
}
}
```

`_return_Ping` has no associated type list. The error is

```
/home/anders05/Dev/sdbusplus/sdbusplus/message/types.hpp:198:72: error: no matching function for call to ‘type_id_multiple()’
         details::type_id_multiple<details::type_id_downcast_t<Args>...>(),
                                                                        ^
/home/anders05/Dev/sdbusplus/sdbusplus/message/types.hpp:187:56: note: candidate: template<class T, class ... Args> constexpr auto sdbusplus::message::types::details::type_id_multiple()
 template <typename T, typename ...Args> constexpr auto type_id_multiple()
                                                        ^
/home/anders05/Dev/sdbusplus/sdbusplus/message/types.hpp:187:56: note:   template argument deduction/substitution failed:
/home/anders05/Dev/sdbusplus/sdbusplus/message/types.hpp:198:72: note:   couldn't deduce template parameter ‘T’
         details::type_id_multiple<details::type_id_downcast_t<Args>...>(),
                                                                        ^
/home/anders05/Dev/dbus-examples/sdbusplus/src/.../.../.../TestService/server.cpp:64:20: error: invalid use of void expression
                 >());
```
