### ISSUE TITLE
Signal property names are not exposed

### ISSUE THREAD

**Issue by BrainStone** [openbmc/sdbusplus#35]
I have configured a signal like this:

```yml
signals:
  - name: StatusChanged
    description: >
      Signal indicating that the status of the VPN connection changed
    properties:
      - name: OldStatus
        type: enum[self.State]
        description: >
          Identifies the actual state the VPN-Controller was in before this signal was sent.
      - name: OldTargetStatus
        type: enum[self.TargetState]
        description: >
          The current target state of the VPN-Controller before this signal was sent.
          Same as the 'TargetStatus' property.
      - name: OldDetails
        type: string
        description: >
          Contains additional infos before this signal was sent. Like up-/downtime or additional error messages when the
          `Status` return value is `Unknown` or `Error`
      - name: Status
        type: enum[self.State]
        description: >
          Identifies the actual state the VPN-Controller currently is in.
      - name: TargetStatus
        type: enum[self.TargetState]
        description: >
          The current target state of the VPN-Controller.
          Same as the 'TargetStatus' property.
      - name: Details
        type: string
        description: >
          Contains additional infos. Like up-/downtime or additional error messages when the `Status` return value is
          `Unknown` or `Error`
```

But when running the program and introspecting, the signal shows like this:

```
    signals:
      StatusChanged(s arg_0,
                    s arg_1,
                    s arg_2,
                    s arg_3,
                    s arg_4,
                    s arg_5);
```
